// SPDX-License-Identifier: Apache-2.0
/**
 * geo7 codec — JavaScript port of the Python codec.
 * Direct cell indexing over a bounding box, encoded in base-28.
 *
 * Ported from the geo7 Python reference (codec.py, alphabet.py, bboxes.py).
 *
 * The region table is the FROZEN data in ./regions.gen.js (a mirror of
 * regions.v1.json), generated by tools/gen-regions.mjs from Natural Earth 1:50m.
 * This file is the ALGORITHM only; the data is frozen. See docs/SPEC.md.
 */

import { BBOXES, CELLS, COUNTRY_NAMES } from "./regions.gen.js?v=105";

const ALPHABET = "0123456789cdefhjkmnpqrtuvwxy";
const BASE = 28;
const INDEX = {};
for (let i = 0; i < ALPHABET.length; i++) {
  INDEX[ALPHABET[i]] = i;
}

const TARGET_M = 18.0;

function getBBox(country, region) {
  country = country.toUpperCase();
  if (region) {
    const key = `${country}-${region.toUpperCase()}`;
    if (BBOXES[key]) return { key, bbox: BBOXES[key] };
  }
  if (BBOXES[country]) return { key: country, bbox: BBOXES[country] };
  return null;
}

function getSupportedCountries() {
  return Object.keys(BBOXES).sort();
}

// The latitude within [minLat, maxLat] closest to the equator. Longitude metres
// per degree are LARGEST there, so sizing lon cells at this latitude makes every
// cell ≤ targetM across the whole box (exactly targetM at the equator-most edge,
// finer toward the poles). Guarantees precision is never worse than targetM.
function _equatorMostLat(minLat, maxLat) {
  if (minLat <= 0 && maxLat >= 0) return 0;
  return Math.abs(minLat) < Math.abs(maxLat) ? minLat : maxLat;
}

// Read the FROZEN grid dimensions for a region. These integers are precomputed
// once by tools/gen-regions.mjs and stored in regions.gen.js. The code↔point
// path therefore never calls cos()/log() — the only platform-dependent functions
// — so every conforming implementation reads identical integers and produces
// bit-identical codes, in any language. See docs/SPEC.md §4.
function _cells(key) {
  const c = CELLS[key];
  if (!c) throw new Error(`No frozen cell counts for region ${key}`);
  return { latCells: c[0], lonCells: c[1], numChars: c[2] };
}

function encodeBits(val, numChars) {
  const chars = [];
  for (let i = 0; i < numChars; i++) {
    chars.push(ALPHABET[val % BASE]);
    val = Math.floor(val / BASE);
  }
  return chars.reverse().join("");
}

function decodeToInt(code) {
  let val = 0;
  for (const ch of code) {
    const lower = ch.toLowerCase();
    if (!(lower in INDEX)) {
      throw new Error(`Invalid character: '${ch}'`);
    }
    val = val * BASE + INDEX[lower];
  }
  return val;
}

function encode(lat, lon, country, region) {
  const entry = getBBox(country, region);
  if (!entry) {
    throw new Error(`No bounding box for country=${country} region=${region || ''}`);
  }
  const [minLat, maxLat, minLon, maxLon] = entry.bbox;

  if (lat < minLat || lat > maxLat || lon < minLon || lon > maxLon) {
    throw new Error(`Coordinates (${lat}, ${lon}) outside bounding box for ${entry.key}`);
  }

  const latSpan = maxLat - minLat;
  const lonSpan = maxLon - minLon;

  const { latCells, lonCells, numChars } = _cells(entry.key);

  let latCell = Math.floor((lat - minLat) / latSpan * latCells);
  let lonCell = Math.floor((lon - minLon) / lonSpan * lonCells);
  latCell = Math.min(latCell, latCells - 1);
  lonCell = Math.min(lonCell, lonCells - 1);

  const cellIndex = latCell * lonCells + lonCell;
  return {
    code: encodeBits(cellIndex, numChars),
    country: entry.key,
    latCell,
    lonCell,
    latCells,
    lonCells,
    numChars,
  };
}

function decode(code, country, region) {
  const entry = getBBox(country, region);
  if (!entry) {
    throw new Error(`No bounding box for country=${country} region=${region || ''}`);
  }
  const [minLat, maxLat, minLon, maxLon] = entry.bbox;
  const latSpan = maxLat - minLat;
  const lonSpan = maxLon - minLon;

  const { latCells, lonCells } = _cells(entry.key);
  const cellIndex = decodeToInt(code);

  const latCell = Math.floor(cellIndex / lonCells);
  const lonCell = cellIndex % lonCells;

  const latResult = minLat + (latCell + 0.5) / latCells * latSpan;
  const lonResult = minLon + (lonCell + 0.5) / lonCells * lonSpan;

  return { lat: latResult, lon: lonResult };
}

function estimatePrecision(country, region) {
  const entry = getBBox(country, region);
  if (!entry) return null;
  const [minLat, maxLat, minLon, maxLon] = entry.bbox;
  const latSpan = maxLat - minLat;
  const lonSpan = maxLon - minLon;
  const { latCells, lonCells, numChars } = _cells(entry.key);

  // Display-only metres-per-cell (NOT in the code path). Report the COARSEST cell
  // (at the equator-most edge) — the guaranteed precision bound.
  const refLat = _equatorMostLat(minLat, maxLat);
  const latMPerDeg = 111320.0;
  const lonMPerDeg = 111320.0 * Math.cos(Math.abs(refLat) * Math.PI / 180);

  const latResolutionM = (latSpan * latMPerDeg) / latCells;
  const lonResolutionM = (lonSpan * lonMPerDeg) / lonCells;

  return {
    latM: latResolutionM,
    lonM: lonResolutionM,
    areaM2: latResolutionM * lonResolutionM,
    latCells,
    lonCells,
    totalCells: latCells * lonCells,
    numChars,
  };
}

// Detect region from lat/lon by checking which bbox contains the point.
// Boxes overlap (rectangles), so prefer a more-specific sub-region (key with "-")
// and, among matches, the smallest box. Best-effort only; a shared code always
// carries its region prefix, so this is for the map-tap / GPS convenience paths.
function detectCountry(lat, lon) {
  let best = null, bestArea = Infinity, bestSpecific = false;
  for (const [key, bbox] of Object.entries(BBOXES)) {
    const [minLat, maxLat, minLon, maxLon] = bbox;
    if (lat >= minLat && lat <= maxLat && lon >= minLon && lon <= maxLon) {
      const specific = key.includes("-");
      const area = (maxLat - minLat) * (maxLon - minLon);
      if ((specific && !bestSpecific) || (specific === bestSpecific && area < bestArea)) {
        best = key; bestArea = area; bestSpecific = specific;
      }
    }
  }
  return best;
}

export {
  ALPHABET, BASE, INDEX, BBOXES, CELLS, COUNTRY_NAMES, TARGET_M,
  encode, decode, estimatePrecision, detectCountry,
  getBBox, getSupportedCountries,
};
